<?php

    function recipes_form_alter(&$form, &$form_state, $form_id){
        if ($form_id == 'recipe_node_form') {
            $form['menu']['#access'] = 0;
            $form['revision_information']['#access'] = 0;
            $form['author']['#access'] = 0;
            $form['options']['#access'] = 0;
            $form['comment_settings']['#access'] = 0;
            $form['comment_settings']['comment']['#default_value'] = 1;
        }

    }
